INSERT INTO platform_courses (title, description, category, level, duration, skill_outcome, is_coming_soon, is_published, order_index) VALUES
('Web3 Fundamentals', 'Understand blockchains, wallets, and the decentralized web.', 'Foundations', 'Beginner', '2 hours', 'Navigate the Web3 ecosystem confidently', false, true, 1),
('Mastering Crypto Wallets', 'Set up, secure, and use wallets like a pro.', 'Foundations', 'Beginner', '1.5 hours', 'Manage assets safely across chains', false, true, 2),
('DeFi Essentials', 'Learn lending, borrowing, and yield strategies.', 'Foundations', 'Beginner', '3 hours', 'Use DeFi protocols confidently', true, true, 3),
('Web3 Marketing Fundamentals', 'Learn the unique dynamics of marketing in Web3.', 'Marketing & Growth', 'Beginner', '2.5 hours', 'Create effective Web3 marketing campaigns', false, true, 4),
('Twitter/X Growth for Web3', 'Build your personal brand and grow your audience.', 'Marketing & Growth', 'Intermediate', '2 hours', 'Grow to 10K+ engaged followers', false, true, 5),
('Meme Coin Marketing Mastery', 'Viral strategies for token launches and community hype.', 'Marketing & Growth', 'Advanced', '4 hours', 'Launch and market meme tokens', true, true, 6),
('Crypto Trading Basics', 'Learn charts, indicators, and entry/exit strategies.', 'Trading & Alpha', 'Beginner', '3 hours', 'Execute profitable trades', false, true, 7),
('Onchain Analysis', 'Read blockchain data to find alpha opportunities.', 'Trading & Alpha', 'Intermediate', '4 hours', 'Identify trends before they go mainstream', true, true, 8),
('Advanced DeFi Trading', 'Leverage, perpetuals, and advanced DeFi strategies.', 'Trading & Alpha', 'Advanced', '5 hours', 'Trade across DeFi protocols', true, true, 9),
('NFT Creation & Monetization', 'Create, mint, and sell your digital art and collectibles.', 'Creator Economy', 'Beginner', '3 hours', 'Launch your first NFT collection', false, true, 10),
('Web3 Content Monetization', 'Monetize newsletters, videos, and podcasts with crypto.', 'Creator Economy', 'Intermediate', '2.5 hours', 'Build sustainable creator income', true, true, 11),
('Introduction to Vibecoding', 'Build Web3 apps using AI and no-code tools.', 'Vibecoding & No-Code', 'Beginner', '3 hours', 'Create functional dApps without coding', false, true, 12),
('AI-Powered App Building', 'Use AI tools to prototype and build faster.', 'Vibecoding & No-Code', 'Intermediate', '4 hours', 'Ship products 10x faster', true, true, 13),
('Solidity Fundamentals', 'Write your first smart contracts on Ethereum.', 'Development', 'Beginner', '6 hours', 'Deploy smart contracts to mainnet', false, true, 14),
('Full-Stack dApp Development', 'Build complete decentralized applications.', 'Development', 'Intermediate', '10 hours', 'Launch production-ready dApps', true, true, 15),
('Smart Contract Security', 'Audit and secure smart contracts from vulnerabilities.', 'Development', 'Advanced', '8 hours', 'Identify and fix security issues', true, true, 16),
('Web3 Community Building', 'Build and grow engaged crypto communities.', 'Community & DAO', 'Beginner', '3 hours', 'Manage thriving Discord servers', false, true, 17),
('DAO Operations & Governance', 'Run effective decentralized organizations.', 'Community & DAO', 'Intermediate', '4 hours', 'Contribute to DAO governance', true, true, 18),
('Web3 Sales & BD', 'Close deals and build partnerships in crypto.', 'Sales & Partnerships', 'Intermediate', '3 hours', 'Land enterprise Web3 clients', true, true, 19),
('Crypto Research Methods', 'Conduct thorough research on projects and protocols.', 'Research & Data', 'Intermediate', '4 hours', 'Write professional research reports', true, true, 20),
('AI Tools for Web3', 'Leverage AI to automate and scale Web3 work.', 'AI & Automation', 'Beginner', '2 hours', 'Automate repetitive tasks with AI', false, true, 21),
('Yield Farming Strategies', 'Maximize returns across DeFi protocols.', 'Onchain & DeFi', 'Intermediate', '4 hours', 'Build diversified yield portfolios', true, true, 22),
('Web3 Leadership', 'Lead teams and projects in the decentralized world.', 'Leadership & Strategy', 'Advanced', '5 hours', 'Build and lead remote Web3 teams', true, true, 23),
('Freelancing in Web3', 'Find clients and get paid in crypto worldwide.', 'Freelancing', 'Beginner', '2 hours', 'Land your first Web3 freelance gig', false, true, 24),
('Global Crypto Payments', 'Invoice and receive payments across borders.', 'Freelancing', 'Intermediate', '1.5 hours', 'Get paid from anywhere seamlessly', true, true, 25),
('Web3 Project Management', 'Manage crypto projects from ideation to launch.', 'Project Management', 'Intermediate', '4 hours', 'Ship Web3 products on time', true, true, 26);