// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chmddvsbvhmwhfbvzlwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobWRkdnNidmhtd2hmYnZ6bHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMDIzOTQsImV4cCI6MjA4NDU3ODM5NH0.MfEapdU9CogG59Q-0evvi7wF07qcFC8PwxKijfOQZXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});